---
title: "viz_1"
author: "chuhan wang_cw3747"
date: "2025-09-25"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggridges)
library(p8105.datasets)
data("weather_df")
```

```{r}
ggplot(data = weather_df, mapping = aes(x = tmin, y = tmax)) +
  geom_point()
```

```{r}
weather_df  |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

```{r}
ggp_weather_scatterplot = 
  weather_df  |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

ggp_weather_scatterplot
```

```{r}
weather_df  |>
  filter(is.na(tmax))
```

## Fancier scatterplot
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE)
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name, size = prcp), alpha = 0.3) +
  geom_smooth(se = FALSE)
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.3, size = 0.74) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)

weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.3, size = 0.74) +
  geom_smooth(se = FALSE) +
  facet_grid(name ~ .)
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = 0.3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```

## LA
```{r}
library(dplyr)
library(ggplot2)

weather_df |>
  filter(name == "CentralPark_NY") |>
  mutate(
    tmax_fahr = tmax * (9/5) + 32,
    tmin_fahr = tmin * (9/5) + 32
  ) |>
  ggplot(aes(x = tmin_fahr, y = tmax_fahr)) +
  geom_point() +
  geom_smooth(se = FALSE, method = "lm")
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) +
  geom_smooth(se = FALSE) +
  geom_point()
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
   geom_point(color = "purple")
```

```{r}
weather_df |>
  ggplot(aes(x = tmin)) +
  geom_histogram(color = "white", fill = "blue")
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, color = name)) +
  geom_histogram()

weather_df |>
  ggplot(aes(x = tmin, fill = name)) +
  geom_histogram()
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, fill = name)) +
  geom_histogram() +
  facet_grid(name ~ .)
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, fill = name)) +
  geom_density(alpha = 0.2)
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
    geom_boxplot(aes(fill = name))
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, fill = name)) +
  geom_violin()
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y=name)) +
  geom_density_ridges()
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, fill = name)) +
  geom_density(alpha = 0.2)
```

```{r}
weather_df |>
  filter(prcp > 5, prcp < 1000) |>
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = 0.2)
```

## Saving Plot
```{r}
ggp_weather_violin =
  weather_df |>
  ggplot(aes(x = name, y = tmin, fill = name)) +
  geom_violin()

ggp_weather_violin

ggsave("plots/violin_plots.pdf", ggp_weather_violin,
       width = 8, height = 6)
```
embedding plots
```{r, fig.width = 6, fig.height = 4}
ggp_weather_violin
```
